public with sharing class WFM_Constants {

    public static final String WFN_NAMED_CREDENTIAL = 'WFNService';
    public static final String STATUS_COMPLETED = 'Completed';
    public static final String STATUS_PENDING = 'Pending';
    public static final String STATUS_CLOSED = 'Closed';
    public static final String STATUS_ERROR = 'Error';
    public static final String NO_MESSAGE_RECEIVED = 'No Message Received';
    
}